pipeline:
  trigger:
    image: metwork/drone-downstream-specific-image:latest
    pull: true
    secrets: [ downstream_token, downstream_server ]
    repositories:
      - metwork-framework/mfextaddon_python2@${DRONE_BRANCH}
      - metwork-framework/mfextaddon_mapserver@${DRONE_BRANCH}
      - metwork-framework/mfextaddon_vim@${DRONE_BRANCH}
      - metwork-framework/mfextaddon_scientific@${DRONE_BRANCH}
      - metwork-framework/docker-mfextaddon_python3_ia-centos7-buildimage@${DRONE_BRANCH}
      - metwork-framework/mfextaddon_python3_ia@${DRONE_BRANCH}
    when:
      event: push
      branch: [ master, integration, release_*, experimental* ]

branches: [ master, integration, release_*, experimental* ]
